project:
  type: website
  output-dir: docs

website:
  title: "Zhenwei.com"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: About Me
      - href: about.qmd
        text: Projects
      - href: hobbies.qmd
        text: Hobbies
      - href: reflection.qmd
        text: Reflection
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



